version: "3.3"
services:
  assistant-ui:
    container_name: assistant-ui-demo
    build: .
    restart: always
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ASSISTANT_ID=${ASSISTANT_ID}
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=8501
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=alp@cerebrumtechnologies.com
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
networks:
  default:
    external:
      name: ${NETWORK_NAME}